<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserIDTextbox</name>
   <tag></tag>
   <elementGuidId>649a09f6-c2de-4c7b-b9d6-bba4601575bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[4]/div/div/div[2]/div[1]/div[2]/div[2]/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
